<?xml version="1.0" encoding="utf-8"?><Database Name="Crud_Linq" Class="LinqDCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Turo;Initial Catalog=Crud_Linq;Integrated Security=True;Encrypt=False" SettingsObjectName="CRUD_Con_Linq_y_SQL.Properties.Settings" SettingsPropertyName="Crud_LinqConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Empresa" Member="Empresas">
    <Type Name="Empresa">
      <Column Name="idEmpresa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreEmpresa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Empresa_Empleado" Member="Empleados" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="Empleado" />
    </Type>
  </Table>
  <Table Name="dbo.Empleado" Member="Empleados">
    <Type Name="Empleado">
      <Column Name="idEmpleado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreEmpleado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellidoEmpleado" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idEmpresa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Empleado_Cargo_Empleado" Member="Cargo_Empleados" ThisKey="idEmpleado" OtherKey="idEmpleado" Type="Cargo_Empleado" />
      <Association Name="Empresa_Empleado" Member="Empresa" ThisKey="idEmpresa" OtherKey="idEmpresa" Type="Empresa" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Cargo" Member="Cargos">
    <Type Name="Cargo">
      <Column Name="idCargo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreCargo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_Cargo_Empleado" Member="Cargo_Empleados" ThisKey="idCargo" OtherKey="idCargo" Type="Cargo_Empleado" />
    </Type>
  </Table>
  <Table Name="dbo.Cargo_Empleado" Member="Cargo_Empleados">
    <Type Name="Cargo_Empleado">
      <Column Name="idCargoEmpleado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCargo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cargo_Cargo_Empleado" Member="Cargo" ThisKey="idCargo" OtherKey="idCargo" Type="Cargo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Empleado_Cargo_Empleado" Member="Empleado" ThisKey="idEmpleado" OtherKey="idEmpleado" Type="Empleado" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>